<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="site-info d-flex col-12 flex-column flex-md-row">

  <span class="copy"><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
  <span class="created">Created by <a href="https://www.21digital.agency/" target="_blank">21Digital</a></span>

</div><!-- end copyright -->


<script type="text/javascript" xml="space">
require([
    'jquery'
], function ($) {
  // Hide Header on on scroll down
  var didScroll;
  var lastScrollTop = 0;
  var delta = 5;
  var navbarHeight = $('.site-header').outerHeight();

  $(window).scroll(function(event){
      didScroll = true;
  });

  setInterval(function() {
      if (didScroll) {
          hasScrolled();
          didScroll = false;
      }
  }, 250);

  function hasScrolled() {
      var st = $(this).scrollTop();

      // Make sure they scroll more than delta
      if(Math.abs(lastScrollTop - st) <= delta)
          return;

      // If they scrolled down and are past the navbar, add class .nav-up.
      // This is necessary so you never see what is "behind" the navbar.
      if (st > lastScrollTop && st > navbarHeight){
          // Scroll Down
          $('.site-header').removeClass('nav-down').addClass('nav-up');
      } else {
          // Scroll Up
          if(st + $(window).height() < $(document).height()) {
              $('.site-header').removeClass('nav-up').addClass('nav-down');
          }
      }

      lastScrollTop = st;
  }
});
</script>
