
	<div class="centered-content">
		<div class="newsletter-cols d-flex flex-column flex-md-row">
			<div class="col-l col-md-6 d-flex flex-column justify-content-center align-center">
				<h5>Newsletter</h5>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum efficitur eleifend.
					Nunc eget bibendum justo, sit amet malesuada dui.</p>
				<ul>
					<li><a href="#"><img class="img-fluid" src="<?php echo $this->getViewFileUrl('images/icons/facebook.png'); ?>"></a></li>
					<li><a href="#"><img class="img-fluid" src="<?php echo $this->getViewFileUrl('images/icons/twitter.png'); ?>"></a></li>
				</ul>
			</div>
			<div class="col-r col-12 col-md-6 d-flex justify-content-center align-center">
				<form class="signup align-self-center">
					<input type="text" placeholder="Enter email address">
					<button type="submit">Submit</button>
				</form>
			</div>
		</div>
	</div>
