<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Basket'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="actions">

        <?php if ($block->shouldRenderQuantity()): ?>

        <p><?= /* @escapeNotVerified */ __('Quantity:') ?></p>

                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />


        <?php endif; ?>

            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="add-to btn orange-solid"
                    id="product-addtocart-button">
              <?= /* @escapeNotVerified */ $buttonTitle ?>
            </button>
            <?= $block->getChildHtml('', true) ?>


</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
