<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>

      Availability: <span class="instock"><?= /* @escapeNotVerified */ __('In stock') ?></span>

    <?php else: ?>

      Availability: <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>

    <?php endif; ?>
<?php endif; ?>
